### ISSUE TITLE
AlchemyAPIDailyLimitExceededException

### ISSUE THREAD

**Issue by Alexander1967muc** [baywet/AlchemyAPIClient#2]
Hello there,

first of all, I really like your library. Good work!

I'm having an issue though when handling exceptions. It seems that the current version is not properly assigning the exception type when a Limit-exceeced-exception happens.
Instead of throwing AlchemyAPIDailyLimitExceededException, AlchemyAPIServiceCallException is thrown with the error message stating "daily-transaction-limit-exceeded".
While this can be handled in code, it would be nicer if the proper exception is thrown.

Cheers
Alexander

**Comment by baywet** [comment]
Hi Alexander,
Thanks for your interest and support in the lib.
Sorry about the late reply
Do you feel like you could submit a PR for that? or do you prefer me to fix it?
Thanks

**Comment by baywet** [comment]
I just quickly fixed that issue. Released today.
Just update to 1.5.1602.151
Thanks for telling me

**Comment by Alexander1967muc** [comment]
Hi Vincent,

thank you very much for addressing this issue!

Kind regards
Alexander

Von: Vincent BIRET [mailto:notifications@github.com]
Gesendet: Dienstag, 16. Februar 2016 05:50
An: baywet/AlchemyAPIClient
Cc: Roethinger, Alexander
Betreff: Re: [AlchemyAPIClient] AlchemyAPIDailyLimitExceededException (#2)

I just quickly fixed that issue. Released today.
Just update to 1.5.1602.151
Thanks for telling me
